const SUPABASE_URL='https://zrfryijgnuzayfywsmgj.supabase.co';
const SUPABASE_ANON='sb_publishable_Zr8X41awfjECwZCtvCh7nQ_qNfOuQkt';
const GATEWAY=`${SUPABASE_URL}/functions/v1/ai-api-gateway`;
const supabase=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON);
const state={page:'Dashboard',keys:[],models:[],usage:[],session:null,loading:true};const app=document.querySelector('#app');
async function init(){try{const {data,error}=await supabase.auth.getSession();if(error)throw error;state.session=data.session;await loadData();}catch(e){console.error(e)}finally{state.loading=false;render()}supabase.auth.onAuthStateChange(async(_e,s)=>{state.session=s;await loadData();render()});handleOAuthCallback()}
async function handleOAuthCallback(){if(location.search.includes('code=')){const {error}=await supabase.auth.exchangeCodeForSession(new URLSearchParams(location.search).get('code'));if(error)console.error(error);history.replaceState({},'',location.pathname)}}
async function loadData(){if(!state.session){state.keys=[];state.usage=[];return}const [k,u]=await Promise.all([supabase.from('api_keys').select('id,name,key_prefix,revoked_at,created_at,last_used_at').order('created_at',{ascending:false}),supabase.from('api_usage').select('id,provider,model,status_code,input_tokens,output_tokens,latency_ms,created_at').order('created_at',{ascending:false}).limit(100)]);state.keys=k.data||[];state.usage=u.data||[]}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(){if(state.loading){app.innerHTML='<div class="loading">Loading AI API Provider…</div>';return}const pages=['Dashboard','API Keys','Playground','Models','Documentation','Usage'];app.innerHTML=`<div class="shell"><aside class="side"><div class="brand">AI API Provider</div><nav class="nav">${pages.map(p=>`<button class="${state.page===p?'active':''}" onclick="go('${p}')">${p}</button>`).join('')}</nav><div class="sidefoot"><span class="badge">Supabase</span><span class="badge">Gateway</span></div></aside><main class="main"><div class="top"><div><h1>${state.page}</h1><div class="muted">Secure OpenAI-compatible AI gateway</div></div>${state.session?`<button class="btn secondary" onclick="signOut()">Sign out</button>`:`<button class="btn" onclick="signIn()">Continue with Google</button>`}</div>${content()}</main></div>`}
function go(p){state.page=p;render();if(p==='Models')loadModels(false)}
function content(){if(!state.session)return `<div class="hero card"><div class="heroicon">✦</div><h2>AI API Provider</h2><p class="muted">Create your own API keys and access Groq + OpenRouter through one secure OpenAI-compatible gateway.</p><button class="btn" onclick="signIn()">Continue with Google</button><p class="small muted">Your provider master keys stay server-side.</p></div>`;
if(state.page==='Dashboard')return `<div class="grid"><div class="card"><span class="muted">Active API keys</span><div class="stat">${state.keys.filter(k=>!k.revoked_at).length}</div></div><div class="card"><span class="muted">Requests</span><div class="stat">${state.usage.length}</div></div><div class="card"><span class="muted">Providers</span><div class="stat">2</div><div class="muted">Groq + OpenRouter</div></div><div class="card"><span class="muted">Streaming</span><div class="stat">ON</div></div></div><div class="card"><h2>Quick start</h2><div class="steps"><div><b>1. Create an API key</b><p class="muted">Open API Keys and generate a secret.</p></div><div><b>2. Choose a model</b><p class="muted">Browse the live provider model list.</p></div><div><b>3. Test it</b><p class="muted">Use Playground or the documented endpoint.</p></div></div></div>`;
if(state.page==='API Keys')return `<div class="card"><h2>Create API key</h2><p class="muted">The full secret is shown only once. Only its SHA-256 hash is stored.</p><div class="row"><input id="keyName" class="input" placeholder="Key name, e.g. Production App"><button class="btn" onclick="createKey()">Generate key</button></div></div><div class="card"><h2>Your keys</h2>${state.keys.length?state.keys.map(k=>`<div class="keyrow"><div><b>${esc(k.name)}</b><div class="muted mono">${esc(k.key_prefix)}•••••••• · ${new Date(k.created_at).toLocaleString()}</div></div>${k.revoked_at?'<span class="badge">Revoked</span>':`<button class="btn danger" onclick="revokeKey('${k.id}')">Revoke</button>`}</div>`).join(''):'<p class="muted">No API keys yet.</p>'}</div>`;
if(state.page==='Playground')return `<div class="card"><div><label>Model</label><select id="model" class="input">${state.models.length?state.models.slice(0,100).map(m=>`<option value="${esc(m.id)}">${esc(m.id)} · ${esc(m.provider)}</option>`).join(''):'<option>Load models first</option>'}</select></div><textarea id="prompt" class="input" rows="7" placeholder="Write your prompt..."></textarea><div class="row"><button class="btn" onclick="play()">Run request</button><button class="btn secondary" onclick="loadModels(true)">Load models</button></div><pre id="out" class="code">Response will appear here.</pre></div>`;
if(state.page==='Models')return `<div class="card"><div class="row"><h2 style="flex:1">Provider models</h2><button class="btn" onclick="loadModels(true)">Refresh</button></div><input id="modelSearch" class="input" oninput="renderModels()" placeholder="Search models..."><div id="modelList" class="modelgrid">${renderModelList()}</div></div>`;
if(state.page==='Documentation')return `<div class="card"><h2>Chat Completions</h2><p>Send a generated key as a Bearer token. The endpoint is OpenAI-compatible.</p><pre class="code">POST ${GATEWAY}\nAuthorization: Bearer YOUR_API_KEY\nContent-Type: application/json\n\n{\n  "model": "MODEL_ID",\n  "messages": [{"role":"user","content":"Hello"}],\n  "stream": true\n}</pre><h3>JavaScript</h3><pre class="code">const response = await fetch('${GATEWAY}', {\n  method: 'POST',\n  headers: { Authorization: 'Bearer YOUR_API_KEY', 'Content-Type':'application/json' },\n  body: JSON.stringify({model:'MODEL_ID',messages:[{role:'user',content:'Hello'}],stream:true})\n});</pre><p class="muted">Never put Groq/OpenRouter master keys in frontend code.</p></div>`;
const total=state.usage.reduce((n,x)=>n+(x.input_tokens||0)+(x.output_tokens||0),0);return `<div class="grid"><div class="card"><span class="muted">Requests</span><div class="stat">${state.usage.length}</div></div><div class="card"><span class="muted">Total tokens</span><div class="stat">${total}</div></div></div><div class="card"><h2>Recent requests</h2>${state.usage.length?`<div class="table">${state.usage.map(x=>`<div class="tr"><span>${esc(x.provider)}</span><span class="mono">${esc(x.model)}</span><span>${x.status_code}</span><span>${x.latency_ms??'-'} ms</span><span>${new Date(x.created_at).toLocaleString()}</span></div>`).join('')}</div>`:'<p class="muted">No requests yet.</p>'}</div>`}
function renderModelList(){const q=(document.querySelector('#modelSearch')?.value||'').toLowerCase();const arr=state.models.filter(m=>(m.id||'').toLowerCase().includes(q));return arr.length?arr.slice(0,200).map(m=>`<div class="model"><b>${esc(m.id)}</b><span class="badge">${esc(m.provider)}</span></div>`).join(''):'<p class="muted">No models loaded yet.</p>'}function renderModels(){const el=document.querySelector('#modelList');if(el)el.innerHTML=renderModelList()}
async function signIn(){const {error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+location.pathname,queryParams:{access_type:'offline',prompt:'select_account'}}});if(error)alert(error.message)}async function signOut(){await supabase.auth.signOut();state.session=null;render()}
function randomKey(){const b=new Uint8Array(32);crypto.getRandomValues(b);return 'sk_ai_'+Array.from(b,x=>x.toString(16).padStart(2,'0')).join('')}
async function hashKey(v){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return Array.from(new Uint8Array(b),x=>x.toString(16).padStart(2,'0')).join('')}
async function createKey(){const name=document.querySelector('#keyName')?.value.trim()||'Untitled key';const raw=randomKey(),hash=await hashKey(raw);const {error}=await supabase.from('api_keys').insert({user_id:state.session.user.id,name,key_prefix:raw.slice(0,12),key_hash:hash});if(error){alert(error.message);return}await loadData();prompt('Copy your new API key. It will not be shown again:',raw);render()}
async function revokeKey(id){if(!confirm('Revoke this API key?'))return;const {error}=await supabase.from('api_keys').update({revoked_at:new Date().toISOString()}).eq('id',id);if(error)alert(error.message);await loadData();render()}
function getRawKey(){let k=sessionStorage.getItem('ai_api_key');if(!k)k=prompt('Paste one generated API key:');if(k)sessionStorage.setItem('ai_api_key',k.trim());return k?.trim()}
async function loadModels(goModels=true){const k=getRawKey();if(!k)return;const r=await fetch(`${GATEWAY}/models`,{headers:{Authorization:`Bearer ${k}`}});const d=await r.json().catch(()=>({}));if(!r.ok){alert(d?.error?.message||'Model request failed');return}state.models=d.data||[];if(goModels){state.page='Models';render()}else render()}
async function play(){const out=document.querySelector('#out'),k=getRawKey();if(!k){out.textContent='API key required.';return}const promptText=document.querySelector('#prompt').value.trim();if(!promptText){out.textContent='Write a prompt first.';return}const model=document.querySelector('#model').value;if(!model||model==='Load models first'){out.textContent='Load models first.';return}out.textContent='';const r=await fetch(GATEWAY,{method:'POST',headers:{Authorization:`Bearer ${k}`,'Content-Type':'application/json'},body:JSON.stringify({model,messages:[{role:'user',content:promptText}],stream:true})});if(!r.ok){out.textContent=await r.text();return}if(!r.body){out.textContent=await r.text();return}const reader=r.body.getReader(),decoder=new TextDecoder();let buf='';while(true){const {done,value}=await reader.read();if(done)break;buf+=decoder.decode(value,{stream:true});const lines=buf.split('\n');buf=lines.pop()||'';for(const line of lines){if(!line.startsWith('data:'))continue;const data=line.slice(5).trim();if(data==='[DONE]')continue;try{const j=JSON.parse(data);out.textContent+=j.choices?.[0]?.delta?.content||j.choices?.[0]?.message?.content||''}catch{}}}}
init();