const state={page:'Dashboard',keys:[],models:[]};
const app=document.querySelector('#app');
function render(){const pages=['Dashboard','API Keys','Playground','Models','Documentation','Usage'];app.innerHTML=`<div class="shell"><aside class="side"><div class="brand">AI API Provider</div><nav class="nav">${pages.map(p=>`<button class="${state.page===p?'active':''}" onclick="go('${p}')">${p}</button>`).join('')}</nav></aside><main class="main"><div class="top"><div><h1>${state.page}</h1><div class="muted">Secure AI API gateway</div></div><button class="btn" onclick="signIn()">Google Sign in</button></div>${content()}</main></div>`}
function go(p){state.page=p;render()}
function content(){if(state.page==='Dashboard')return `<div class="grid"><div class="card"><span class="muted">API Keys</span><div class="stat">${state.keys.length}</div></div><div class="card"><span class="muted">Providers</span><div class="stat">2</div><div class="muted">Groq + OpenRouter</div></div><div class="card"><span class="muted">Streaming</span><div class="stat">ON</div></div></div><div class="card"><h2>Production architecture</h2><p class="muted">Browser → your API key → secure server → Supabase validation/logging → Groq/OpenRouter → streaming response.</p></div>`;
if(state.page==='API Keys')return `<div class="card"><h2>Create API key</h2><input id="keyName" class="input" placeholder="Key name, e.g. My App"><button class="btn" onclick="createKey()">Generate key</button></div><div class="card"><h2>Your keys</h2>${state.keys.length?state.keys.map((k,i)=>`<div class="card"><b>${k.name}</b><div class="muted">${k.prefix}•••••••• · ${k.created}</div><button class="btn danger" onclick="revokeKey(${i})">Revoke</button></div>`).join(''):'<p class="muted">No keys yet.</p>'}</div>`;
if(state.page==='Playground')return `<div class="card"><label>Model</label><input id="model" class="input" value="openai/gpt-4o-mini"><textarea id="prompt" class="input" rows="8" placeholder="Write your prompt..."></textarea><button class="btn" onclick="play()">Run request</button><pre id="out" class="code">Response will appear here.</pre></div>`;
if(state.page==='Models')return `<div class="card"><h2>Provider models</h2><p class="muted">Production backend will dynamically cache Groq and OpenRouter model catalogs. No provider secret is exposed here.</p><button class="btn" onclick="loadModels()">Refresh models</button><pre id="models" class="code">${state.models.join('\n')||'Connect backend to load models.'}</pre></div>`;
if(state.page==='Documentation')return `<div class="card"><h2>API</h2><p>Use your generated key as a Bearer token. Provider master keys stay server-side.</p><pre class="code">POST /v1/chat/completions\nAuthorization: Bearer YOUR_API_KEY\nContent-Type: application/json\n\n{\n  "model":"MODEL_ID",\n  "messages":[{"role":"user","content":"Hello"}],\n  "stream":true\n}</pre></div>`;
return `<div class="card"><h2>Usage</h2><p class="muted">Usage records will come from Supabase api_usage after the API route is connected.</p><div class="grid"><div><span class="muted">Requests</span><div class="stat">0</div></div><div><span class="muted">Tokens</span><div class="stat">0</div></div></div></div>`}
function createKey(){const n=document.querySelector('#keyName').value.trim()||'Untitled key';const raw='sk_ai_'+crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-','');state.keys.push({name:n,prefix:raw.slice(0,12),created:new Date().toLocaleString()});alert('Demo key generated. Production version will show the secret once and store only its hash.');render()}
function revokeKey(i){state.keys.splice(i,1);render()}
function signIn(){alert('Google OAuth is wired to Supabase in the production auth route after OAuth credentials/redirect URL are configured.')}
function play(){document.querySelector('#out').textContent='Backend endpoint pending: /v1/chat/completions';}
function loadModels(){state.models=['Groq: dynamically fetched /openai/v1/models','OpenRouter: dynamically fetched /api/v1/models'];render()}
render();
